// Alerts 
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// User Actions
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const AUTH_ERROR = 'AUTH_ERROR';

export const REGISTER_SUCCES = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN_STUDENT_SUCCESS = 'LOGIN_STUDENT_SUCCESS';
export const LOGIN_ADMIN_SUCCESS = 'LOGIN_ADMIN_SUCCESS';

export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';


// Students
export const GET_STUDENTS = 'GET_STUDENTS';
export const GET_FILTERED_STUDENTS = 'GET_STUDENTS';

export const GET_STUDENT = 'GET_STUDENT';
export const DELETE_STUDENTS = 'DELETE_STUDENTS';
export const DELETE_STUDENT = 'DELETE_STUDENT';

// Schools
export const GET_SCHOOLS = 'GET_SCHOOLS';
export const DELETE_SCHOOL = 'DELETE_SCHOOL';
export const ADD_SCHOOL = 'ADD_SCHOOL';


// Donations
export const GET_DONATONS = 'GET_DONATONS';
export const GET_DONATONS_BY_SCHOOL = 'GET_DONATONS_BY_SCHOOL';
export const GET_DONATONS_BY_SCHOOL_ID = 'GET_DONATONS_BY_SCHOOL_ID';
export const GET_DONATONS_BY_STUDENT = 'GET_DONATONS_BY_STUDENT';
export const GET_DONATONS_BY_STUDENT_ID = 'GET_DONATONS_BY_STUDENT_ID';

  

export const ADD_DONATION = 'ADD_DONATION';
export const DONATION_ERROR = 'DONATION_ERROR';
export const GET_CURRENT_STUDENT_DONATION = 'GET_CURRENT_STUDENT_DONATION';


// Sidebar 
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';


// Admin Settings 
export const CREATE_ADMIN = 'CREATE_ADMIN';
export const DELETE_ADMIN = 'DELETE_ADMIN';
export const UPDATE_SETTING = 'UPDATE_SETTING';
export const LOAD_SETTING = 'LOAD_SETTING';